# Generated by Django 5.2.4 on 2025-07-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Sarlavha')),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='Havola')),
                ('preview', models.ImageField(upload_to='images/', verbose_name='Eskiz')),
                ('description', models.TextField(max_length=200, verbose_name='Izoh')),
                ('source', models.CharField(max_length=30, verbose_name='Reklama yoki post egasi')),
            ],
        ),
    ]
