# Generated by Django 5.2.4 on 2025-08-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_sher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50, verbose_name='Yozuvchi ismi va familyasi')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Eskiz')),
                ('description', models.TextField(max_length=200, verbose_name='Izoh')),
                ('file', models.FileField(blank=True, null=True, upload_to='book_files/', verbose_name='Kitob fayli')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('audio', models.FileField(blank=True, null=True, upload_to='book_audio/', verbose_name='Audio')),
                ('audio_duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Audio davomiyligi')),
                ('file_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fayl turi')),
            ],
        ),
        migrations.AlterField(
            model_name='sher',
            name='sarlavha',
            field=models.CharField(max_length=20),
        ),
    ]
