# Generated by Django 5.2.4 on 2025-08-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_book_alter_sher_sarlavha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Philosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='file_type',
        ),
    ]
