# Generated by Django 5.2.4 on 2025-08-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_philosophy_remove_book_file_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sher',
            options={'ordering': ['-sana']},
        ),
        migrations.AddField(
            model_name='sher',
            name='janr',
            field=models.CharField(blank=True, choices=[('lirik', 'Lirik'), ('epik', 'Epik'), ('dramatik', 'Dramatik'), ('satirik', 'Satirik')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sher',
            name='korishlar_soni',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sher',
            name='manba',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sher',
            name='reyting',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sher',
            name='til',
            field=models.CharField(default="O'zbekcha", max_length=50),
        ),
        migrations.AlterField(
            model_name='sher',
            name='sarlavha',
            field=models.CharField(max_length=100),
        ),
    ]
