# Generated by Django 5.2.4 on 2025-08-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_sher_options_sher_janr_sher_korishlar_soni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sher',
            name='korishlar_soni',
        ),
        migrations.RemoveField(
            model_name='sher',
            name='reyting',
        ),
        migrations.AddField(
            model_name='sher',
            name='haqida',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Tanqid va izohlar tarixi , O‘qish va taqdimotlar , Keyingi nashrlar , Tahrirlar va o‘zgarishlar  , Dastlabki nashr , Voqealar fonida , Yozilgan sana ,'),
        ),
    ]
