# Generated by Django 5.2.4 on 2025-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_sher_korishlar_soni_remove_sher_reyting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Izoh'),
        ),
    ]
