# Generated by Django 5.2.4 on 2025-10-11 10:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profil rasmi')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?998?\\d{9,12}$')], verbose_name='Telefon raqam')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol'), ('O', 'Boshqa')], max_length=1, null=True, verbose_name='Jinsi')),
                ('interested_genres', models.TextField(blank=True, help_text='Masalan: fantastika, detektiv, sarguzasht, tarixiy', null=True, verbose_name='Qiziqqan janrlar (vergul bilan ajrating)')),
                ('books_read', models.TextField(blank=True, help_text='Masalan: Alkimyogar, O‘tkan kunlar, Jinoyat va jazo', null=True, verbose_name='O‘qigan kitoblar')),
                ('bio', models.TextField(blank=True, help_text='Ijodiy ishingiz, hayotingiz yoki maqsadlaringiz haqida yozing', null=True, verbose_name='Bio (o‘zingiz haqingizda qisqacha)')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kasb / Lavozim')),
                ('workplace', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ish joyi')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Shaxsiy sayt')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='So‘nggi faollik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Profil yaratilgan sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
    ]
